#!/bin/bash
#SBATCH -J 6000K  # Job name
#SBATCH -o myjob.o%j       # Name of stdout output file
#SBATCH -e myjob.e%j       # Name of stderr error file
#SBATCH -p development          # Queue (partition) name
#SBATCH -N 2          # Total # of nodes (must be 1 for serial)
#SBATCH -n 100          # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 00:10:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=zsong@memphis.edu
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A TG-DMR170076    # Allocation name (req'd if you have more than 1)

module load intel

mpicxx -std=c++11 -mkl=sequential  -O2 main.cpp CONSTANT.cpp BFGS.cpp EnergyForce.cpp Group.cpp IO.cpp Tool.cpp -o main

ibrun ./main

rm main

# ---------------------------------------------------
